blueprint:
  name: TRVZB Fenster- und Zeitsteuerung
  description: >
    Steuert SONOFF TRVZB ausschließlich per Home Assistant.
    Hersteller-Automatik wird ignoriert. Fenster offen = Heizung wirklich aus.
  domain: automation

  input:
    trv:
      name: TRVZB Thermostat
      selector:
        target:
          entity:
            integration: mqtt
            domain: climate

    schedule_entity:
      name: Heiz-Zeitplan
      description: schedule.* Helper, wann geheizt werden soll
      selector:
        entity:
          domain: schedule

    window_sensor:
      name: Fenstersensor(e)
      description: Binary-Sensor oder Gruppe für Fensterstatus
      selector:
        entity:
          domain:
            - binary_sensor
            - group

    comfort_temp:
      name: Komfort-Temperatur (°C)
      default: 21.0
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    window_off_temp:
      name: Temperatur bei Fenster offen (°C)
      description: Wird beim offenen Fenster gesetzt (z.B. 5–8 °C)
      default: 5.0
      selector:
        number:
          min: 5
          max: 15
          step: 0.5
          unit_of_measurement: "°C"

    window_open_delay:
      name: Verzögerung nach Fenster-Öffnen
      default: "00:02:00"
      selector:
        duration: {}

    window_close_delay:
      name: Verzögerung nach Fenster-Schließen
      default: "00:01:00"
      selector:
        duration: {}

triggers:
  # Fenster-Status
  - trigger: state
    entity_id: !input window_sensor

  # Zeitplan-Änderung
  - trigger: state
    entity_id: !input schedule_entity

  # Sicherheits-Fallback: regelmäßig nachziehen
  - trigger: time_pattern
    minutes: "/10"

variables:
  trv: !input trv
  schedule_entity: !input schedule_entity
  window_sensor: !input window_sensor
  comfort_temp: !input comfort_temp
  window_off_temp: !input window_off_temp
  window_open_delay: !input window_open_delay
  window_close_delay: !input window_close_delay

conditions: []

actions:
  - choose:
      # 1) Fenster offen -> TRVZB hart "aus" / Minimaltemp, solange offen
      - conditions:
          - condition: state
            entity_id: !input window_sensor
            state: "on"
        sequence:
          - delay: !input window_open_delay
          - condition: state
            entity_id: !input window_sensor
            state: "on"
          # Hersteller-Automatik umgehen: manuell auf Minimalwert setzen
          - action: climate.set_hvac_mode
            target: !input trv
            data:
              hvac_mode: "heat"
          - action: climate.set_temperature
            target: !input trv
            data:
              temperature: !input window_off_temp

      # 2) Fenster zu -> Steuerung ausschließlich per HA-Zeitplan
      - conditions:
          - condition: state
            entity_id: !input window_sensor
            state: "off"
        sequence:
          - delay: !input window_close_delay
          - condition: state
            entity_id: !input window_sensor
            state: "off"
          - choose:
              # a) Zeitplan EIN -> Komfort
              - conditions:
                  - condition: state
                    entity_id: !input schedule_entity
                    state: "on"
                sequence:
                  - action: climate.set_hvac_mode
                    target: !input trv
                    data:
                      hvac_mode: "heat"
                  - action: climate.set_temperature
                    target: !input trv
                    data:
                      temperature: !input comfort_temp

              # b) Zeitplan AUS -> TRVZB aus/minimal
              - conditions:
                  - condition: state
                    entity_id: !input schedule_entity
                    state: "off"
                sequence:
                  - action: climate.set_hvac_mode
                    target: !input trv
                    data:
                      hvac_mode: "heat"
                  - action: climate.set_temperature
                    target: !input trv
                    data:
                      temperature: !input window_off_temp
            default: []

mode: restart
