blueprint:
  name: TRVZB Heizungssteuerung mit Delta-Hysterese, Fenster & Override
  description: >
    Heizungssteuerung für Thermostate (z.B. Sonoff TRVZB) mit Delta-Hysterese.
    Unterstützt optional einen externen Temperatursensor, Zeitplan,
    Override, Absenktemperatur und Fensterabschaltung bis 0 °C.
    Autor: Patrick Kohnke – www.defcon-1.de
  domain: automation
  author: Patrick Kohnke
  source_url: https://raw.githubusercontent.com/Defcon-1-de/TRVZB/refs/heads/main/TRVZB.yaml

  input:
    thermostat:
      name: Thermostat / Climate-Entity
      selector:
        entity:
          domain: climate

    temperature_sensor:
      name: Externer Temperatursensor (optional)
      description: Wenn leer, wird die interne Temperatur des Thermostats genutzt.
      default: []
      selector:
        entity:
          domain: sensor

    window_sensor:
      name: Fenstersensor (optional)
      description: Fenster offen = Heizung auf Fenster-Abschalttemperatur.
      default: []
      selector:
        entity:
          domain:
            - binary_sensor
            - group

    schedule_entity:
      name: Zeitplan (optional)
      description: schedule-Helper, der Heizphasen steuert.
      default: []
      selector:
        entity:
          domain: schedule

    override_entity:
      name: Override (optional)
      description: z.B. input_boolean oder Switch für manuelle Regelung.
      default: []
      selector:
        entity:
          domain:
            - input_boolean
            - switch

    last_setpoint_store:
      name: Speicher für letztes Komfort-Setpoint (optional)
      description: input_number, in dem das letzte Komfort-Setpoint persistiert wird.
      default: []
      selector:
        entity:
          domain: input_number

    comfort_temp:
      name: Komfort-Temperatur (°C)
      default: 21.0
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    setback_temp:
      name: Absenktemperatur außerhalb Heizzeiten (°C)
      description: Temperatur, auf die außerhalb der Heizzeiten abgesenkt wird.
      default: 17.0
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    window_off_temp:
      name: Temperatur bei Fenster offen (°C)
      description: Darf 0 sein, wenn das Thermostat es unterstützt.
      default: 0.0
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    delta_hysteresis:
      name: Delta-Hysterese (°C)
      description: Differenz zwischen Soll- und Ist-Temperatur, ab der geheizt wird.
      default: 3.0
      selector:
        number:
          min: 0.5
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    window_open_delay:
      name: Verzögerung nach Fenster-Öffnen
      default: "00:02:00"
      selector:
        duration: {}

    window_close_delay:
      name: Verzögerung nach Fenster-Schließen
      default: "00:01:00"
      selector:
        duration: {}

triggers:
  - trigger: state
    entity_id: !input temperature_sensor
    id: temp_ext

  - trigger: state
    entity_id: !input thermostat
    id: temp_int

  - trigger: state
    entity_id: !input window_sensor
    id: window

  - trigger: state
    entity_id: !input schedule_entity
    id: schedule

  - trigger: state
    entity_id: !input override_entity
    id: override

  - trigger: time_pattern
    minutes: "/10"
    id: periodic

variables:
  thermostat: !input thermostat
  temperature_sensor: !input temperature_sensor
  window_sensor: !input window_sensor
  schedule_entity: !input schedule_entity
  override_entity: !input override_entity
  last_setpoint_store: !input last_setpoint_store

  comfort_temp: !input comfort_temp
  setback_temp: !input setback_temp
  window_off_temp: !input window_off_temp
  delta_hysteresis: !input delta_hysteresis
  window_open_delay: !input window_open_delay
  window_close_delay: !input window_close_delay

  current_temp: >-
    {% if temperature_sensor != [] %}
      {{ states(temperature_sensor) | float(0) }}
    {% else %}
      {{ state_attr(thermostat, 'current_temperature') | float(0) }}
    {% endif %}

  last_comfort_temp: >-
    {% if last_setpoint_store != [] %}
      {{ states(last_setpoint_store) | float(comfort_temp) }}
    {% else %}
      {{ comfort_temp }}
    {% endif %}

conditions: []

actions:
  - choose:
      # 1) Fenster offen -> immer Fenster-Abschalttemperatur, höchste Priorität
      - conditions:
          - condition: template
            value_template: >
              {{ window_sensor != [] and is_state(window_sensor, 'on') }}
        sequence:
          - delay: !input window_open_delay
          - condition: template
            value_template: >
              {{ window_sensor != [] and is_state(window_sensor, 'on') }}
          - action: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - action: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: !input window_off_temp

      # 2) Override aktiv -> keine automatische Regelung (Fensterlogik oben bleibt)
      - conditions:
          - condition: template
            value_template: >
              {{ override_entity != [] and is_state(override_entity, 'on') }}
        sequence: []

      # 3) Normalbetrieb (kein Override, Fenster zu oder nicht vorhanden)
      - conditions:
          - condition: template
            value_template: >
              {{ override_entity == [] or is_state(override_entity, 'off') }}
        sequence:
          - choose:
              # 3a) Fenster vorhanden, aber zu
              - conditions:
                  - condition: template
                    value_template: >
                      {{ window_sensor == [] or is_state(window_sensor, 'off') }}
                sequence:
                  - choose:
                      # Heizzeit (Schedule an oder nicht vorhanden) -> Komfort-Logik
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity == [] or is_state(schedule_entity, 'on') }}
                        sequence:
                          # Heizung EIN, wenn Komfort-Soll - Ist >= Delta
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: >
                                      {{ (comfort_temp - current_temp) >= delta_hysteresis }}
                                sequence:
                                  - choose:
                                      - conditions:
                                          - condition: template
                                            value_template: "{{ last_setpoint_store != [] }}"
                                        sequence:
                                          - action: input_number.set_value
                                            target:
                                              entity_id: !input last_setpoint_store
                                            data:
                                              value: "{{ comfort_temp }}"
                                    default: []
                                  - action: climate.set_hvac_mode
                                    target:
                                      entity_id: !input thermostat
                                    data:
                                      hvac_mode: heat
                                  - action: climate.set_temperature
                                    target:
                                      entity_id: !input thermostat
                                    data:
                                      temperature: !input comfort_temp

                          # Heizung AUS, wenn Ist >= Komfort-Soll
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: >
                                      {{ current_temp >= comfort_temp }}
                                sequence:
                                  - action: climate.set_hvac_mode
                                    target:
                                      entity_id: !input thermostat
                                    data:
                                      hvac_mode: "off"
                            default: []

                      # Absenkbetrieb (Schedule aus) -> Setback-Temperatur
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity != [] and is_state(schedule_entity, 'off') }}
                        sequence:
                          - action: climate.set_hvac_mode
                            target:
                              entity_id: !input thermostat
                            data:
                              hvac_mode: heat
                          - action: climate.set_temperature
                            target:
                              entity_id: !input thermostat
                            data:
                              temperature: !input setback_temp
                    default: []

              # 3b) Fenster war offen, jetzt zu -> Rückkehr zu Komfort/Setback nach Delay
              - conditions:
                  - condition: template
                    value_template: >
                      {{ window_sensor != [] and is_state(window_sensor, 'off') }}
                sequence:
                  - delay: !input window_close_delay
                  - condition: template
                    value_template: >
                      {{ window_sensor == [] or is_state(window_sensor, 'off') }}
                  - choose:
                      # Nach Fenster zu + Heizzeit -> Komfort-Temp (oder gespeichertes Setpoint)
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity == [] or is_state(schedule_entity, 'on') }}
                        sequence:
                          - action: climate.set_hvac_mode
                            target:
                              entity_id: !input thermostat
                            data:
                              hvac_mode: heat
                          - action: climate.set_temperature
                            target:
                              entity_id: !input thermostat
                            data:
                              temperature: "{{ last_comfort_temp }}"
                      # Nach Fenster zu + Absenkbetrieb -> Setback-Temp
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity != [] and is_state(schedule_entity, 'off') }}
                        sequence:
                          - action: climate.set_hvac_mode
                            target:
                              entity_id: !input thermostat
                            data:
                              hvac_mode: heat
                          - action: climate.set_temperature
                            target:
                              entity_id: !input thermostat
                            data:
                              temperature: !input setback_temp
            default: []
    default: []

mode: single
