blueprint:
  name: Heizungssteuerung mit Wochen-Schedule, Fenster, Override, Außentemperatur, Snapshot und Eco
  description: >
    Steuert ein Thermostat anhand eines Wochen-Schedules, einem Fensterkontakt/-gruppe,
    optionalem manuellen Override, einem Außentemperatur-Differenzwert und einer Eco-Absenktemperatur.
    Beim Öffnen eines Fensters wird der aktuelle Heiz-Zustand des Thermostats als Szene gespeichert
    und die Heizung ausgeschaltet. Nach dem Schließen wird der gespeicherte Zustand wiederhergestellt
    oder je nach Zeitplan auf Komfort- bzw. Eco-Temperatur gestellt.
  domain: automation
  author: "Defcon-1.de / Patrick Kohnke"

  input:
    thermostat_entity:
      name: Heizungsgerät
      description: Das zu steuernde Thermostat (z.B. Sonoff TRVZB über Zigbee2MQTT)
      selector:
        entity:
          domain: climate

    target_temp:
      name: Komfort-Temperatur bei aktivem Zeitplan (Fallback)
      description: >
        Komfort-Solltemperatur, auf die gestellt wird, wenn beim Wiederanheizen kein gültiger Snapshot
        vorhanden ist (z.B. nach Neustart).
      default: 22
      selector:
        number:
          min: 16
          max: 26
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider

    eco_temp:
      name: Eco-/Absenktemperatur außerhalb des Zeitplans
      description: >
        Temperatur, die gehalten werden soll, wenn der Wochen-Schedule aus ist,
        das Fenster geschlossen ist und der Außentemperatur-Check OK ist.
      default: 18
      selector:
        number:
          min: 5
          max: 26
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider

    week_schedule:
      name: Wochen-Schedule
      description: >
        Ein einziger Schedule-Helper, in dem die Zeiten für alle Tage der Woche gepflegt werden.
        Der Schedule muss den Zustand "on" haben, wenn Komfort-Heizen erlaubt sein soll.
      selector:
        entity:
          domain: schedule

    window_entity:
      name: Fensterkontakt oder Fenster-Gruppe
      description: Ein einzelner Fensterkontakt oder eine Gruppe von Kontakten
      selector:
        entity:
          domain: binary_sensor
          device_class: window

    reopen_delay:
      name: Verzögerung nach Fenster-Schließen
      description: Wartezeit nach geschlossenem Fenster, bevor wieder geheizt und ggf. Snapshot wiederhergestellt wird
      default: 30
      selector:
        number:
          min: 0
          max: 300
          step: 5
          unit_of_measurement: "Sekunden"
          mode: slider

    manual_override:
      name: Manueller Override (Automatik pausieren)
      description: >
        Input-Boolean, der die Automatik deaktiviert, wenn er auf EIN steht.
        Z.B. "Heizung Schlafzimmer Override".
