blueprint:
  name: TRVZB Heizungssteuerung mit Delta-Hysterese, Fensterüberwachung & manuellem Override
  description: >
    Heizkörperregelung für das Sonoff TRVZB mit Delta-Hysterese,
    Heizzeiten, Absenkbetrieb, Fensterkontakt und optionalem Override.
    Autor: Patrick Kohnke – www.defcon-1.de
  domain: automation
  author: Patrick Kohnke
  source_url: https://raw.githubusercontent.com/Defcon-1-de/TRVZB/refs/heads/main/TRVZB.yaml

  input:
    thermostat:
      name: Thermostat
      selector:
        entity:
          domain: climate

    temperature_sensor:
      name: Externer Temperatursensor (optional)
      description: Wenn leer, wird die interne Temperatur des Thermostats genutzt.
      default: []
      selector:
        entity:
          domain: sensor

    window_sensor:
      name: Fenstersensor (optional)
      description: Fenster offen = Absenkung auf Fenster-Temperatur.
      default: []
      selector:
        entity:
          domain:
            - binary_sensor
            - group

    schedule_entity:
      name: Heiz-Zeitplan (optional)
      description: schedule-Helper für Komfort-Zeiten.
      default: []
      selector:
        entity:
          domain: schedule

    override_entity:
      name: Override (optional)
      description: Schalter für manuelle Regelung.
      default: []
      selector:
        entity:
          domain:
            - input_boolean
            - switch

    last_setpoint_store:
      name: Speicher für letztes Komfort-Setpoint (optional)
      description: input_number zur Ablage des letzten Komfort-Setpoints.
      default: []
      selector:
        entity:
          domain: input_number

    comfort_temp:
      name: Komfort-Temperatur (°C)
      default: 21.0
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    setback_temp:
      name: Absenktemperatur außerhalb Heizzeiten (°C)
      default: 17.0
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    window_off_temp:
      name: Temperatur bei Fenster offen (°C)
      default: 0.0
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    delta_hysteresis:
      name: Delta-Hysterese (°C)
      description: Komfort-Soll minus Ist, ab der geheizt wird.
      default: 3.0
      selector:
        number:
          min: 0.5
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    window_open_delay:
      name: Verzögerung Fenster auf
      default: "00:0:15"
      selector:
        duration: {}

    window_close_delay:
      name: Verzögerung Fenster zu
      default: "00:01:15"
      selector:
        duration: {}

triggers:
  - trigger: state
    entity_id: !input temperature_sensor
    id: temp_ext

  - trigger: state
    entity_id: !input thermostat
    id: temp_int

  - trigger: state
    entity_id: !input window_sensor
    id: window

  - trigger: state
    entity_id: !input schedule_entity
    id: schedule

  - trigger: state
    entity_id: !input override_entity
    id: override

  - trigger: time_pattern
    minutes: "/10"
    id: periodic

variables:
  thermostat: !input thermostat
  temperature_sensor: !input temperature_sensor
  window_sensor: !input window_sensor
  schedule_entity: !input schedule_entity
  override_entity: !input override_entity
  last_setpoint_store: !input last_setpoint_store

  comfort_temp: !input comfort_temp
  setback_temp: !input setback_temp
  window_off_temp: !input window_off_temp
  delta_hysteresis: !input delta_hysteresis
  window_open_delay: !input window_open_delay
  window_close_delay: !input window_close_delay

  current_temp: >-
    {% if temperature_sensor != [] %}
      {{ states(temperature_sensor) | float(0) }}
    {% else %}
      {{ state_attr(thermostat, 'current_temperature') | float(0) }}
    {% endif %}

  last_comfort_temp: >-
    {% if last_setpoint_store != [] %}
      {{ states(last_setpoint_store) | float(comfort_temp) }}
    {% else %}
      {{ comfort_temp }}
    {% endif %}

conditions: []

actions:
  - choose:
      # Fenster offen
      - conditions:
          - condition: template
            value_template: >
              {{ window_sensor != [] and is_state(window_sensor, 'on') }}
        sequence:
          - delay: !input window_open_delay
          - condition: template
            value_template: >
              {{ window_sensor != [] and is_state(window_sensor, 'on') }}
          - action: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - action: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: !input window_off_temp

      # Override aktiv
      - conditions:
          - condition: template
            value_template: >
              {{ override_entity != [] and is_state(override_entity, 'on') }}
        sequence: []

      # Normalbetrieb
      - conditions:
          - condition: template
            value_template: >
              {{ override_entity == [] or is_state(override_entity, 'off') }}
        sequence:
          - choose:
              # Fenster zu
              - conditions:
                  - condition: template
                    value_template: >
                      {{ window_sensor == [] or is_state(window_sensor, 'off') }}
                sequence:
                  - choose:
                      # Heizzeit (Komfort)
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity == [] or is_state(schedule_entity, 'on') }}
                        sequence:
                          # Heizen, wenn Delta erreicht
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: >
                                      {{ (comfort_temp - current_temp) >= delta_hysteresis }}
                                sequence:
                                  - choose:
                                      - conditions:
                                          - condition: template
                                            value_template: "{{ last_setpoint_store != [] }}"
                                        sequence:
                                          - action: input_number.set_value
                                            target:
                                              entity_id: !input last_setpoint_store
                                            data:
                                              value: "{{ comfort_temp }}"
                                    default: []
                                  - action: climate.set_hvac_mode
                                    target:
                                      entity_id: !input thermostat
                                    data:
                                      hvac_mode: heat
                                  - action: climate.set_temperature
                                    target:
                                      entity_id: !input thermostat
                                    data:
                                      temperature: !input comfort_temp

                          # Aus, wenn Komfort erreicht
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: >
                                      {{ current_temp >= comfort_temp }}
                                sequence:
                                  - action: climate.set_hvac_mode
                                    target:
                                      entity_id: !input thermostat
                                    data:
                                      hvac_mode: "off"
                            default: []

                      # Absenkbetrieb (Heizzeit aus)
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity != [] and is_state(schedule_entity, 'off') }}
                        sequence:
                          - action: climate.set_hvac_mode
                            target:
                              entity_id: !input thermostat
                            data:
                              hvac_mode: heat
                          - action: climate.set_temperature
                            target:
                              entity_id: !input thermostat
                            data:
                              temperature: !input setback_temp
                    default: []

              # Fenster gerade wieder zu
              - conditions:
                  - condition: template
                    value_template: >
                      {{ window_sensor != [] and is_state(window_sensor, 'off') }}
                sequence:
                  - delay: !input window_close_delay
                  - condition: template
                    value_template: >
                      {{ window_sensor == [] or is_state(window_sensor, 'off') }}
                  - choose:
                      # nach Fenster zu + Heizzeit
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity == [] or is_state(schedule_entity, 'on') }}
                        sequence:
                          - action: climate.set_hvac_mode
                            target:
                              entity_id: !input thermostat
                            data:
                              hvac_mode: heat
                          - action: climate.set_temperature
                            target:
                              entity_id: !input thermostat
                            data:
                              temperature: "{{ last_comfort_temp }}"
                      # nach Fenster zu + Absenkbetrieb
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ schedule_entity != [] and is_state(schedule_entity, 'off') }}
                        sequence:
                          - action: climate.set_hvac_mode
                            target:
                              entity_id: !input thermostat
                            data:
                              hvac_mode: heat
                          - action: climate.set_temperature
                            target:
                              entity_id: !input thermostat
                            data:
                              temperature: !input setback_temp
            default: []
    default: []

mode: single
